version: "3.3"

networks:
  backend:

services:
  api-service:
    container_name: api-service
    image: api-service
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 8085:80
    depends_on:
      - mysqldb
      - redis
    networks:
      - backend
    environment:
      SPRING_PROFILES_ACTIVE: test
  frontend-service:
    container_name: frontend-service
    image: frontend-service
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 8086:3000
    depends_on:
      - api-service
    networks:
      - backend
  mysqldb:
    image: mysql:5.7
    ports:
      - 3311:3306
    restart: always
    volumes:
      - ./mysql_data_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: contact
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6385:6379
    networks:
      - backend